l_info(paste0("IOTDB_USER         : ", Sys.getenv("IOTDB_USER")))
l_info(paste0("IOTCSTATISTICS_USER: ", Sys.getenv("IOTCSTATISTICS_USER")))
l_info(paste0("WP_CE_RAISED_USER  : ", Sys.getenv("WP_CE_RAISED_USER")))

set_credentials_for_db(IOTDB,          Sys.getenv("IOTDB_USER"), Sys.getenv("IOTDB_PASSWORD"))
set_credentials_for_db(IOTCSTATISTICS, Sys.getenv("IOTCSTATISTICS_USER"), Sys.getenv("IOTCSTATISTICS_PASSWORD"))
set_credentials_for_db(WP_CE_RAISED,   Sys.getenv("WP_CE_RAISED_USER"), Sys.getenv("WP_CE_RAISED_PASSWORD"))

SUMMARY_CHART_HEIGHT    = 640
GEOREF_CHART_HEIGHT     = 556
SIZE_LINE_CHART_HEIGHT  = GEOREF_CHART_HEIGHT

PLOT_DEFAULT_WIDTH  = 16
PLOT_DEFAULT_HEIGHT =  9

PLOT_PIE_DEFAULT_WIDTH  = PLOT_DEFAULT_WIDTH
PLOT_PIE_DEFAULT_HEIGHT = PLOT_DEFAULT_HEIGHT

DOWNLOAD_PLOT_BUTTON_TEXT = "Download this plot"
DOWNLOAD_DATA_BUTTON_TEXT = "Download this dataset"

NO_UNITS      = NA
NO_CATEGORIES = NA

GRID_RESOLUTIONS = c(#"Original"      = NA,
                     #"1x1 degrees"   = grid_1x1,
                      "5x5 degrees"   = grid_5x5,
                      "10x10 degrees" = grid_10x10,
                      "10x20 degrees" = grid_10x20,
                      "20x20 degrees" = grid_20x20,
                      "30x30 degrees" = grid_30x30)

QUADRANTS = c("All IO"       = "ALLIO",
              "Northwest IO" =  "NWIO",
              "Northeast IO" =  "NEIO",
              "Southeast IO" =  "SEIO",
              "Southwest IO" =  "SWIO",
              "North IO"     =   "NIO",
              "South IO"     =   "SIO",
              "West IO"      =   "WIO",
              "East IO"      =   "EIO")

QUARTERS = c("Q1 - Jan - Mar" = "Q1",
             "Q2 - Apr - Jun" = "Q2",
             "Q3 - Jul - Sep" = "Q3",
             "Q4 - Oct - Dec" = "Q4",
             "Unclassified"   = "UNCL")

QUARTER_CATEGORY = list("Quarter" = C_QUARTER)

EFFORT_CATEGORIES  = list("Fishery type"    = C_FISHERY_TYPE,
                          "Fishery group"   = C_FISHERY_GROUP,
                          "Fishery"         = C_FISHERY,
                          "Gear"            = C_GEAR,
                          "Fleet"           = C_FLEET)

CATCH_CATEGORIES = append(copy(EFFORT_CATEGORIES),
                          list("Species IUCN status"   = C_IUCN_STATUS,
                               "Species working party" = C_SPECIES_WP,
                               "Species group"         = C_SPECIES_GROUP,
                               "Species category"      = C_SPECIES_CATEGORY,
                               "Species"               = C_SPECIES))

SIZE_CATEGORIES = append(list("Raising type" = C_RAISING), CATCH_CATEGORIES)

NOMINAL_CATCH_CATEGORIES = list("IO major area" = C_FISHING_GROUND)
NOMINAL_CATCH_CATEGORIES = append(NOMINAL_CATCH_CATEGORIES, CATCH_CATEGORIES)

EFFORT_CATEGORIES = append(QUARTER_CATEGORY, EFFORT_CATEGORIES)
CATCH_CATEGORIES  = append(QUARTER_CATEGORY, CATCH_CATEGORIES)
SIZE_CATEGORIES   = append(QUARTER_CATEGORY, SIZE_CATEGORIES)

SIZE_STD_CATEGORIES = SIZE_CATEGORIES[-which(names(SIZE_CATEGORIES) == "Raising type")]

initialize_all_species_colors()
initialize_all_gears_colors()

CUSTOM_COLORS = color_table(unique_colors(64))

pie_size_by_resolution = function(resolution) {
  if(resolution == grid_1x1)        return(  .5)
  else if(resolution == grid_10x10) return( 5.0)
  else if(resolution == grid_10x20) return( 5.0)
  else if(resolution == grid_20x20) return(10.0)
  else if(resolution == grid_30x30) return(15.0)

  return(2.5)
}

limits_for_quadrant = function(quadrant) {
  xlim = IO_map_xlim
  ylim = IO_map_ylim

  if(quadrant == "NWIO") { xlim = c(20,  85); ylim = c(-15,  30) }
  if(quadrant == "NEIO") { xlim = c(75, 150); ylim = c(-15,  30) }
  if(quadrant == "SEIO") { xlim = c(75, 150); ylim = c(-60, -15) }
  if(quadrant == "SWIO") { xlim = c(20,  85); ylim = c(-60, -15) }
  if(quadrant ==  "NIO") { xlim = c(20, 150); ylim = c(-15,  30) }
  if(quadrant ==  "SIO") { xlim = c(20, 150); ylim = c(-60, -15) }
  if(quadrant ==  "WIO") { xlim = c(20,  85); ylim = c(-60,  30) }
  if(quadrant ==  "EIO") { xlim = c(75, 150); ylim = c(-60,  30) }

  return (list(xlim = xlim, ylim = ylim))
}

label_for = function(elements, values, description_only = FALSE) {
  results = names(elements[sapply(elements, function(x) { x %in% values})])

  if(description_only) results = sapply(results, function(x) { return(str_replace(x, "[A-Z\\_]+\\s-\\s", ""))} )

  return(results)
}

titolize = function(source, last_update, plot, title) {
  return (plot + ggtitle(label = title, subtitle = subtitle_for_plot(source, last_update)))
}

subtitle_for_plot = function(source, last_update) {
  return(
    paste("Generated by IOTC from", source, "on", now("GMT"), "GMT. Data last updated on", last_update)
  )
}

title_for = function(inputs, plot_name = "DUMMY_PLOT_NAME", units, unit, categories, category) {
  tokens = c(plot_name)

  if(is_available(units)      & is_available(unit))     tokens = append(tokens, c("in", tolower(label_for(units, unit, TRUE))))
  if(is_available(categories) & is_available(category)) tokens = append(tokens, c("by", tolower(label_for(categories, category, TRUE))))

  tokens = append(tokens, paste0("(", serialize_filter(inputs), ")"))

  return (paste0(tokens, collapse = " "))
}

filename_for = function(inputs, plot = "DUMMY_PLOT", units, unit, categories, category) {
  tokens = c(plot)

  if(is_available(units) & is_available(unit)) tokens = append(tokens, unit)
  if(is_available(categories) & is_available(category)) tokens = append(tokens, c("BY", category))

  tokens = append(tokens, serialize_filter(inputs, for_filename = TRUE))

  return (paste0(tokens, collapse = "_"))
}

serialize_filter = function(inputs, for_filename = FALSE) {
  if(for_filename) {
    filter = paste0("[", inputs$period[1], "-", inputs$period[2], "]")

    if(is_available(inputs$fishingGrounds))    filter = paste0(filter, "[", paste0(inputs$fishingGrounds, collapse = "+"), "]")

    if(is_available(inputs$fisheryTypes))      filter = paste0(filter, "[", paste0(inputs$fisheryTypes, collapse = "+"), "]")
    if(is_available(inputs$fisheryGroups))     filter = paste0(filter, "[", paste0(inputs$fisheryGroups, collapse = "+"), "]")
    if(is_available(inputs$fisheries))         filter = paste0(filter, "[", paste0(inputs$fisheries, collapse = "+"), "]")
    if(is_available(inputs$gears))             filter = paste0(filter, "[", paste0(inputs$gears, collapse = "+"), "]")

    if(is_available(inputs$fleets))            filter = paste0(filter, "[", paste0(inputs$fleets, collapse = "+"), "]")

    if(is_available(inputs$IUCNStatus))        filter = paste0(filter, "[", paste0(inputs$IUCNStatus, collapse = "+"), "]")
    if(is_available(inputs$speciesWps))        filter = paste0(filter, "[", paste0(inputs$speciesWps, collapse = "+"), "]")
    if(is_available(inputs$speciesGroups))     filter = paste0(filter, "[", paste0(inputs$speciesGroups, collapse = "+"), "]")
    if(is_available(inputs$speciesCategories)) filter = paste0(filter, "[", paste0(inputs$speciesCategories, collapse = "+"), "]")
    if(is_available(inputs$species))           filter = paste0(filter, "[", paste0(inputs$species, collapse = "+"), "]")
    if(is_available(inputs$raising))           filter = paste0(filter, "[", paste(inputs$raising, collapse = "+"), "]")
  } else {
    filter = paste(inputs$period[1], "-", inputs$period[2])

    if(is_available(inputs$fishingGrounds))    filter = paste(filter, "/", paste0(inputs$fishingGrounds, collapse = " + "))

    if(is_available(inputs$fisheryTypes))      filter = paste(filter, "/", paste(inputs$fisheryTypes, collapse = " + "))
    if(is_available(inputs$fisheryGroups))     filter = paste(filter, "/", paste(inputs$fisheryGroups, collapse = " + "))
    if(is_available(inputs$fisheries))         filter = paste(filter, "/", paste(inputs$fisheries, collapse = " + "))
    if(is_available(inputs$gears))             filter = paste(filter, "/", paste(inputs$gears, collapse = " + "))

    if(is_available(inputs$fleets))            filter = paste(filter, "/", paste(inputs$fleets, collapse = " + "))

    if(is_available(inputs$IUCNStatus))        filter = paste(filter, "/", paste(inputs$IUCNStatus, collapse = " + "))
    if(is_available(inputs$speciesWps))        filter = paste(filter, "/", paste(inputs$speciesWps, collapse = " + "))
    if(is_available(inputs$speciesGroups))     filter = paste(filter, "/", paste(inputs$speciesGroups, collapse = " + "))
    if(is_available(inputs$speciesCategories)) filter = paste(filter, "/", paste(inputs$speciesCategories, collapse = " + "))
    if(is_available(inputs$species))           filter = paste(filter, "/", paste(inputs$species, collapse = " + "))

    if(is_available(inputs$raising))           filter = paste(filter, "/", paste(inputs$raising, collapse = " + "))
  }

  return(filter)
}
